all:
	make -C host
	make -C prime
	make -C aes
	make -C mem
	make -C crypt
	make -C deadloop
	make -C count
	make -C gm_test_enclaves
	make -C seal_data
	make -C seal_data1
	make -C seal_data2
	make -C seal_data3
	make -C seal_data4
	make -C seal_data5
	make -C seal_data6
	make -C seal_data7
	make -C seal_data8

clean:
	make -C host clean
	make -C prime clean
	make -C aes clean
	make -C mem clean
	make -C crypt clean
	make -C deadloop clean
	make -C count clean
	make -C gm_test_enclaves clean
	make -C seal_data clean
	make -C seal_data1 clean
	make -C seal_data2 clean
	make -C seal_data3 clean
	make -C seal_data4 clean
	make -C seal_data5 clean
	make -C seal_data6 clean
	make -C seal_data7 clean
	make -C seal_data8 clean
